# Author: Panagiotis Karamolegkos (UPRC)

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # Role
metadata:
  namespace: he-codeco-netma  # The desired namespace for the CRD
  name: netma-resource-patcher
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]