# Author: Panagiotis Karamolegkos (UPRC)

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: he-codeco-mdm
  name: mdm-resource-patcher
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]