# Author: Panagiotis Karamolegkos (UPRC)

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding # RoleBinding
metadata:
  namespace: he-codeco-mdm  # The desired namespace for the CRD
  name: mdm-resource-patcher-binding
subjects:
- kind: ServiceAccount
  name: default  # Adjust to the correct service account name if different
  namespace: he-codeco-mdm  # The desired namespace for the CRD
roleRef:
  kind: ClusterRole # Role
  name: mdm-resource-patcher
  apiGroup: rbac.authorization.k8s.io